// THIS TESTS ARE GENERATED BY AI

package main

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

func setupTestDB(t *testing.T) *DB {
	t.Helper()

	sqlDB, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("failed to open in-memory database: %v", err)
	}

	db := &DB{sqlDB}

	if _, err := db.Exec("PRAGMA foreign_keys = ON"); err != nil {
		db.Close()
		t.Fatalf("failed to enable foreign keys: %v", err)
	}
	if err := db.InitTables(); err != nil {
		db.Close()
		t.Fatalf("failed to initialize tables: %v", err)
	}
	t.Cleanup(func() {
		db.Close()
	})

	return db
}

func stringPtr(s string) *string {
	return &s
}

func TestRegisterUser(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	params := CreateUserParams{
		Name:     "Test User",
		Email:    "test@example.com",
		Password: "securepassword",
	}

	user, err := db.RegisterUser(ctx, params)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if user.ID == 0 {
		t.Error("expected non-zero user ID")
	}
	if user.Name != params.Name {
		t.Errorf("expected name %q, got %q", params.Name, user.Name)
	}
	if user.Email != params.Email {
		t.Errorf("expected email %q, got %q", params.Email, user.Email)
	}
	if user.CreatedAt == "" {
		t.Error("expected non-empty created_at timestamp")
	}

	_, err = db.RegisterUser(ctx, params)
	if err == nil {
		t.Fatal("expected duplicate email error, got nil")
	}

	if !strings.Contains(err.Error(), "UNIQUE constraint failed") {
		t.Errorf("expected UNIQUE constraint error, got: %v", err)
	}
}

func TestLoginUser(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	email := "user@example.com"
	password := "mypassword"

	_, err := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Auth User",
		Email:    email,
		Password: password,
	})
	if err != nil {
		t.Fatalf("failed to register user: %v", err)
	}

	user, err := db.LoginUser(ctx, LoginParams{
		Email:    email,
		Password: password,
	})
	if err != nil {
		t.Fatalf("expected successful login, got: %v", err)
	}
	if user.Email != email {
		t.Errorf("expected logged in user email %q, got %q", email, user.Email)
	}

	_, err = db.LoginUser(ctx, LoginParams{
		Email:    email,
		Password: "wrongpassword",
	})
	if !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("expected sql.ErrNoRows for wrong password, got: %v", err)
	}

	_, err = db.LoginUser(ctx, LoginParams{
		Email:    "nonexistent@example.com",
		Password: password,
	})
	if !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("expected sql.ErrNoRows for nonexistent user, got: %v", err)
	}
}

func TestCreateExpense(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()
	_, err := db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      999,
		Amount:      42.50,
		Category:    stringPtr("Food"),
		Description: stringPtr("Lunch"),
		Date:        "2026-05-28",
	})
	if err == nil {
		t.Fatal("expected foreign key constraint error, got nil")
	}
	if !strings.Contains(err.Error(), "FOREIGN KEY constraint failed") {
		t.Errorf("expected FOREIGN KEY constraint error, got: %v", err)
	}

	user, err := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Expense Owner",
		Email:    "owner@example.com",
		Password: "password",
	})
	if err != nil {
		t.Fatalf("failed to register user: %v", err)
	}

	params := CreateExpenseParams{
		UserID:      user.ID,
		Amount:      1500.0,
		Category:    stringPtr("Tech"),
		Description: stringPtr("New Keyboard"),
		Date:        "2026-05-28",
	}

	expense, err := db.CreateExpense(ctx, params)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if expense.ID == 0 {
		t.Error("expected non-zero expense ID")
	}
	if expense.UserID != user.ID {
		t.Errorf("expected UserID %d, got %d", user.ID, expense.UserID)
	}
	if expense.Amount != params.Amount {
		t.Errorf("expected amount %f, got %f", params.Amount, expense.Amount)
	}
	if expense.Category == nil || *expense.Category != *params.Category {
		t.Errorf("expected category %v, got %v", params.Category, expense.Category)
	}
	if expense.Description == nil || *expense.Description != *params.Description {
		t.Errorf("expected description %v, got %v", params.Description, expense.Description)
	}
	if expense.Date.Format("2006-01-02") != params.Date {
		t.Errorf("expected date %q, got %q", params.Date, expense.Date)
	}
}

func TestCreateExpenseOptionalFields(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	user, err := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Expense Owner Optional",
		Email:    "optional@example.com",
		Password: "password",
	})
	if err != nil {
		t.Fatalf("failed to register user: %v", err)
	}

	params := CreateExpenseParams{
		UserID:      user.ID,
		Amount:      120.0,
		Category:    nil, // Optional field
		Description: nil, // Optional field
		Date:        "2026-05-28",
	}

	expense, err := db.CreateExpense(ctx, params)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if expense.Category != nil {
		t.Errorf("expected nil Category, got %q", *expense.Category)
	}
	if expense.Description != nil {
		t.Errorf("expected nil Description, got %q", *expense.Description)
	}

	found, err := db.GetExpenseByID(ctx, expense.ID)
	if err != nil {
		t.Fatalf("expected no error getting expense, got %v", err)
	}
	if found.Category != nil {
		t.Errorf("expected Category in DB to be nil, got %q", *found.Category)
	}
	if found.Description != nil {
		t.Errorf("expected Description in DB to be nil, got %q", *found.Description)
	}
}

func TestGetExpenseByID(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	user, _ := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Owner",
		Email:    "owner@example.com",
		Password: "password",
	})

	created, _ := db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      100.0,
		Category:    stringPtr("Books"),
		Description: stringPtr("Golang Book"),
		Date:        "2026-05-28",
	})

	found, err := db.GetExpenseByID(ctx, created.ID)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if found.ID != created.ID || found.Description == nil || *found.Description != "Golang Book" {
		t.Errorf("retrieved unexpected expense: %+v", found)
	}

	_, err = db.GetExpenseByID(ctx, 9999)
	if !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("expected sql.ErrNoRows, got: %v", err)
	}
}

func TestUpdateExpense(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	user, _ := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Owner",
		Email:    "owner@example.com",
		Password: "password",
	})

	created, _ := db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      500.0,
		Category:    stringPtr("Hobbies"),
		Description: stringPtr("Drone parts"),
		Date:        "2026-05-28",
	})

	amount := 750.0
	updateParams := UpdateExpenseParams{
		ID:     created.ID,
		UserID: user.ID,
		Amount: &amount,
	}

	updated, err := db.UpdateExpense(ctx, updateParams)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if updated.Amount != 750.0 {
		t.Errorf("expected updated amount 750.0, got %f", updated.Amount)
	}

	if updated.Category == nil || *updated.Category != "Hobbies" {
		t.Errorf("[ОШИБКА ЛОГИКИ]: Категория изменилась или стерлась: %v", updated.Category)
	}
	if updated.Description == nil || *updated.Description != "Drone parts" {
		t.Errorf("[ОШИБКА ЛОГИКИ]: Описание изменилось или стерлось: %v", updated.Description)
	}
}

func TestDeleteExpense(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	user, _ := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Owner",
		Email:    "owner@example.com",
		Password: "password",
	})

	created, _ := db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      50.0,
		Category:    stringPtr("Coffee"),
		Description: stringPtr("Espresso"),
		Date:        "2026-05-28",
	})

	deleted, err := db.DeleteExpense(ctx, created.ID, user.ID)
	if err != nil {
		t.Fatalf("expected no error on delete, got %v", err)
	}
	if deleted.ID != created.ID {
		t.Errorf("expected deleted ID %d, got %d", created.ID, deleted.ID)
	}

	// Try to delete this expense using a different user ID
	otherUser, _ := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Other User",
		Email:    "other@example.com",
		Password: "password",
	})

	_, err = db.DeleteExpense(ctx, created.ID, otherUser.ID)
	if !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("expected sql.ErrNoRows when deleting other user's expense, got: %v", err)
	}

	_, err = db.GetExpenseByID(ctx, created.ID)
	if !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("expected sql.ErrNoRows after delete, got: %v", err)
	}

	_, err = db.DeleteExpense(ctx, 9999, user.ID)
	if !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("expected sql.ErrNoRows when deleting non-existent, got: %v", err)
	}
}

func TestGetAllExpenses(t *testing.T) {
	db := setupTestDB(t)
	ctx := context.Background()

	user, err := db.RegisterUser(ctx, CreateUserParams{
		Name:     "Filter User",
		Email:    "filter@example.com",
		Password: "password",
	})
	if err != nil {
		t.Fatalf("failed to register user: %v", err)
	}

	now := time.Now()
	dateToday := now.Format("2006-01-02")
	date10DaysAgo := now.AddDate(0, 0, -10).Format("2006-01-02")
	date45DaysAgo := now.AddDate(0, 0, -45).Format("2006-01-02")
	date4MonthsAgo := now.AddDate(0, -4, 0).Format("2006-01-02")

	// Helper to cast CategoryFilter to string
	catGroceries := stringPtr(string(Groceries))
	catUtilities := stringPtr(string(Utilities))

	// 1. Today, Groceries
	_, _ = db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      10.0,
		Category:    catGroceries,
		Description: stringPtr("Milk"),
		Date:        dateToday,
	})

	// 2. 10 days ago, Groceries
	_, _ = db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      20.0,
		Category:    catGroceries,
		Description: stringPtr("Bread"),
		Date:        date10DaysAgo,
	})

	// 3. 45 days ago, Utilities
	_, _ = db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      100.0,
		Category:    catUtilities,
		Description: stringPtr("Electricity"),
		Date:        date45DaysAgo,
	})

	// 4. 4 months ago, Groceries
	_, _ = db.CreateExpense(ctx, CreateExpenseParams{
		UserID:      user.ID,
		Amount:      50.0,
		Category:    catGroceries,
		Description: stringPtr("Steak"),
		Date:        date4MonthsAgo,
	})

	// Helper to convert category string to *CategoryFilter
	toCategoryFilter := func(c string) *CategoryFilter {
		cf := CategoryFilter(c)
		return &cf
	}

	t.Run("Default weekly filter", func(t *testing.T) {
		expenses, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID: user.ID,
			Period: "", // default (weekly)
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if len(expenses) != 1 {
			t.Errorf("expected 1 expense for past week, got %d", len(expenses))
		}
	})

	t.Run("PastWeek filter", func(t *testing.T) {
		expenses, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID: user.ID,
			Period: PastWeek,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if len(expenses) != 1 {
			t.Errorf("expected 1 expense for PastWeek, got %d", len(expenses))
		}
	})

	t.Run("PastMonth filter", func(t *testing.T) {
		expenses, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID: user.ID,
			Period: PastMonth,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		// Expect Today + 10 days ago (2 items)
		if len(expenses) != 2 {
			t.Errorf("expected 2 expenses for PastMonth, got %d", len(expenses))
		}
	})

	t.Run("Past3Month filter", func(t *testing.T) {
		expenses, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID: user.ID,
			Period: Past3Month,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		// Expect Today + 10 days ago + 45 days ago (3 items)
		if len(expenses) != 3 {
			t.Errorf("expected 3 expenses for Past3Month, got %d", len(expenses))
		}
	})

	t.Run("Category filter groceries", func(t *testing.T) {
		expenses, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID:   user.ID,
			Category: toCategoryFilter(string(Groceries)),
			Period:   Past3Month,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		// In Past3Month, we have Today (Groceries) and 10 days ago (Groceries) -> 2 items
		if len(expenses) != 2 {
			t.Errorf("expected 2 groceries in past 3 months, got %d", len(expenses))
		}
	})

	t.Run("Custom date range", func(t *testing.T) {
		start := now.AddDate(0, 0, -15).Format(time.RFC3339)
		end := now.AddDate(0, 0, -5).Format(time.RFC3339)
		expenses, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID:    user.ID,
			Period:    Custom,
			StartDate: &start,
			EndDate:   &end,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		// Expect only 10 days ago expense (1 item)
		if len(expenses) != 1 {
			t.Errorf("expected 1 expense in custom range, got %d", len(expenses))
		}
	})

	t.Run("Custom date range error", func(t *testing.T) {
		_, err := db.GetAllExpenses(ctx, GetExpenseParams{
			UserID: user.ID,
			Period: Custom,
		})
		if err == nil {
			t.Error("expected error for missing custom dates, got nil")
		}
	})
}
